changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Bugs Fixed 🕷
      labels:
        - bug
        - defect
    - title: Enhancements 💡
      labels:
        - enhancement
        - feature
        - improvement
    - title: Other Changes
      labels:
        - "*"
    - title: Dependencies 📦
      labels:
        - dependencies
