name: 'Test Report'

on:
  workflow_run:
    workflows: ['Acceptance']
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          name: Test Report
          artifact: test-results
          path: '*.trx'
          reporter: dotnet-trx
